
project := _fake

import-project:
	rm -rf src/projects/$(project)
	mkdir -p src/projects/$(project)
	node -e "var yaml = require('js-yaml'); var fs = require('fs'); fs.writeFileSync('src/projects/$(project)/rules.ts', '// THIS FILE IS AUTOGENERATED\n// tslint:disable\nexport default ' + JSON.stringify(yaml.safeLoad(fs.readFileSync('projects/$(project)/rules.yaml').toString())))"
	node -e "var yaml = require('js-yaml'); var fs = require('fs'); fs.writeFileSync('src/projects/$(project)/schema.ts', '// THIS FILE IS AUTOGENERATED\n// tslint:disable\nexport default ' + JSON.stringify(yaml.safeLoad(fs.readFileSync('projects/$(project)/schema.json').toString())))"
	node -e "var fs = require('fs'); fs.writeFileSync('src/projects/$(project)/index.ts', '// THIS FILE IS AUTOGENERATED\n// tslint:disable\nimport rules from \'./rules\'; import schema from \'./schema\'; export { rules, schema };')"
