#!/usr/bin/env node

import { rules } from "../../";

// print a lot of rules
export function printReferenceDocs() {

  rules.all.forEach(r => {
    console.log(`
## ${"`" + r.name + "`"}

${r.message}

${r.links ? "\n\n#### More Info:" : ""}

${r.links ? r.links.map(l => `- ${l}`).join("\n") : ""}

${r.examples ? "#### Examples:\n" : ""}
${(r.examples && r.examples.wrong) ? r.examples.wrong.map(e => {
      return "*Incorrect*: " + e.description + "\n\n```yaml" + e.yaml + "\n```\n\n";
    }).join("\n") : ""}

${(r.examples && r.examples.right) ? r.examples.right.map(e => {
      return "*Correct*: " + e.description + "\n\n```yaml" + e.yaml + "\n```\n\n";
    }).join("\n") : ""}
    `);
  });

  console.log();
  console.log();
  console.log();
  console.log(`Autogenerated reference documentation for [Replicated YAML Linter](https://github.com/replicatedhq/replicated-lint)`);
  console.log(`*Generated at ${new Date()}*`);
  console.log();
}

exports.command = "gen";
exports.describe = "";
exports.handler = printReferenceDocs;
