// THIS FILE IS AUTOGENERATED
// tslint:disable
import { YAMLRule } from "../../lint";
const rules: YAMLRule[] = [{"name":"policy-require-string-in-name","type":"error","message":"name have to be string","test":{"AllOf":{"path":"v1","pred":{"Not":{"pred":{"Exists":{"path":"name"}}}}}},"examples":{"wrong":[{"description":"name is empty","yaml":"---\nname: \"\"\n"},{"description":"name is array","yaml":"---\nname: []\n"}],"right":[{"description":"name has a name","yaml":"---\nname: \"Policy name\"\n"}]}}];
export default rules;
