// THIS FILE IS AUTOGENERATED
// tslint:disable
import { JSONSchema4 } from "json-schema";
const schema: JSONSchema4 = {"$schema":"http://json-schema.org/draft-07/schema#","type":"object","properties":{"v1":{"type":"object","properties":{"name":{"type":"string"},"resources":{"type":"object","properties":{"allowed":{"type":"array","items":{"type":"string","pattern":"^(([a-zA-Z0-9]+|\\*\\*?)\\/)*(([a-zA-Z0-9]+|\\*\\*?))$"}},"denied":{"type":"array","items":{"type":"string","pattern":"^(([a-zA-Z0-9]+|\\*\\*?)\\/)*(([a-zA-Z0-9]+|\\*\\*?))$"}}}}},"required":["name","resources"]}},"required":["v1"]};
export default schema;
