// THIS FILE IS AUTOGENERATED
// tslint:disable
import { YAMLRule } from "../../lint";
const rules: YAMLRule[] = [{"name":"spec-prop-unique-keys","type":"error","message":"Entitlement Spec keys must be unique","test":{"ArrayMemberFieldsNotUnique":{"path":"key"}},"examples":{"wrong":[{"description":"spec has duplicated key `my_field`","yaml":"---\n- name: My Field\n  type: string\n  description: My cool field\n  key: my_field\n- name: My Other Field\n  type: number\n  description: some other field\n  key: my_field\n"}],"right":[{"description":"Spec keys have unique names","yaml":"---\n- name: My Field\n  key: my_field\n  description: My cool field\n  type: string\n- name: My Other Field\n  key: my_other_field\n  description: some other field\n  type: number\n"}]}}];
export default rules;